-- MySQL Script generated by MySQL Workbench
-- dom 28 mar 2021 14:47:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cortoTPI
-- -----------------------------------------------------
-- Es un sistema de administracion en biblioteca correspondiente al corto 2 de TPI
-- 

-- -----------------------------------------------------
-- Schema cortoTPI
--
-- Es un sistema de administracion en biblioteca correspondiente al corto 2 de TPI
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cortoTPI` DEFAULT CHARACTER SET cp1256 ;
USE `cortoTPI` ;

-- -----------------------------------------------------
-- Table `cortoTPI`.`abstractusuariodomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cortoTPI`.`abstractusuariodomain` (
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `estadoUsuario` TINYINT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigoPostal` INT NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cortoTPI`.`librodomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cortoTPI`.`librodomain` (
  `isbn` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `numPaginas` INT NOT NULL,
  `fechaAlta` DATE NOT NULL,
  `numDisponibles` INT NOT NULL,
  PRIMARY KEY (`isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cortoTPI`.`ejemplardomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cortoTPI`.`ejemplardomain` (
  `idEjemplar` INT NOT NULL,
  `isbn` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `fechaAdquisicion` DATE NOT NULL,
  `observaciones` VARCHAR(45) NULL,
  `fechaPrestamo` DATE NOT NULL,
  `fechaDevolucion` DATE NOT NULL,
  `estadoEjemplar` VARCHAR(45) NOT NULL,
  `localizacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEjemplar`),
 FOREIGN KEY (`login`)
    REFERENCES `cortoTPI`.`abstractusuariodomain` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY (`isbn`)
    REFERENCES `cortoTPI`.`librodomain` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cortoTPI`.`prestamohistoricodomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cortoTPI`.`prestamohistoricodomain` (
  `idEjemplar` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `fechaPrestamo` DATE NOT NULL,
  `fechaDevolucion` DATE NOT NULL,
  `fechaDevolucionReal` DATE NOT NULL,
  FOREIGN KEY (`login`)
    REFERENCES `cortoTPI`.`abstractusuariodomain` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idEjemplar`)
    REFERENCES `cortoTPI`.`ejemplardomain` (`idEjemplar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cortoTPI`.`reservadomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cortoTPI`.`reservadomain` (
  `isbn` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `tipoFinalizacion` VARCHAR(45) NOT NULL,
  `estadoHistorico` VARCHAR(45) NOT NULL,
  FOREIGN KEY (`login`)
    REFERENCES `cortoTPI`.`abstractusuariodomain` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`isbn`)
    REFERENCES `cortoTPI`.`librodomain` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cortoTPI`.`multadomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cortoTPI`.`multadomain` (
  `login` VARCHAR(45) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `estadoHistorico` VARCHAR(45) NOT NULL,
  FOREIGN KEY (`login`)
    REFERENCES `cortoTPI`.`abstractusuariodomain` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cortoTPI`.`profesordomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cortoTPI`.`profesordomain` (
  `login` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
 FOREIGN KEY (`login`)
    REFERENCES `cortoTPI`.`abstractusuariodomain` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cortoTPI`.`alumnodomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cortoTPI`.`alumnodomain` (
  `login` VARCHAR(45) NOT NULL,
  FOREIGN KEY (`login`)
    REFERENCES `cortoTPI`.`abstractusuariodomain` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cortoTPI`.`bibliotecariodomain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cortoTPI`.`bibliotecariodomain` (
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nif` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
